### ISSUE TITLE
which metrics?

### ISSUE THREAD

**Issue by mpadge** [hypertidy/geodist#1]
here you go @mdsumner - this should be very quick to assemble. We can just start with vectorized C++ implementations of:

1. Haversine
2. Vincenty
3. [Mapbox cheap](https://github.com/mapbox/cheap-ruler-cpp), as explained in [this blog post](https://blog.mapbox.com/fast-geodesic-approximations-with-cheap-ruler-106f229ad016). 

This will all be able to be done quickly with only `Rcpp` dep, but we could even dump that and then be essentially dependency free?

**Comment by mpadge** [comment]
And by the way: `available::available("geodist")` gives the all-clear

**Comment by mdsumner** [comment]
I'm happy with these and Rcpp, for now Rcpp is basically an assumed basic most of the time!

**Comment by mdsumner** [comment]
I'm inclined to default to metres as the basic assumed unit as it is with projections - do you feel strongly for km? 

geosphere is metres but others km (or miles :)

```R
x0 <- cbind(0, 0)
x1 <- cbind(0, 1)
## m  [1] 110574.4
geosphere::distGeo(x0, x1)
## km [1] 110.5731
spDistsN1(x0, x1, longlat = T)
## km [1,] 111.3239
fields::rdist.earth(x0, x1, miles = FALSE)
```

I think we tend to work in m/s as a default rather than km/h and over the years - is there a stronger established convention outside of R?

**Comment by mpadge** [comment]
I'm easy on that, but one advantage of default km would be an ability to offer miles as well. That'd require another param, so we may as well just add `units` and enable ask options, right? I can't really see us facing much of a parameter overload issue

**Comment by mpadge** [comment]
closing this now that the big three have been implemented, and opening a `units` issue to finish the job
