### ISSUE TITLE
Sequential geodist produces different results to paired

### ISSUE THREAD

**Issue by mem48** [hypertidy/geodist#19]
There seem to be different results produced when geodist is used in sequential mode or manually pairing the results
```
# Make example lon/lat points
mat <- matrix(c(-0.193011, 52.15549,
                -0.197722, 52.15395,
                -0.199949, 52.15527,
                -0.199533, 52.15762,
                -0.193205, 52.15757,
                -0.174015, 52.17529)
                , ncol = 2, byrow = TRUE)
colnames(mat) <- c("lon","lat")

# Use sequential mode
dist1 <- geodist::geodist(mat, sequential = TRUE)

# Manually make to and from objects
from <- mat[1:5,]
to <- mat[2:6,]
dist2 <- geodist::geodist(from, to, paired = TRUE)
identical(dist1, dist2) # FALSE
```

**Comment by mpadge** [comment]
Oh  yeah, you are indeed right there. Seems like a pretty mission-critical bug I've buried in there ...

**Comment by mem48** [comment]
It has been causing me a headache all afternoon.

**Comment by mpadge** [comment]
Even more interesting:
``` r
dist3 <- geodist::geodist(mat)
dist3 <- dist3 [which (row (dist3) == (col (dist3) + 1))] # off-diagonal
identical (dist3, dist1) # FALSE
identical (dist3, dist2) # TRUE
```
it's actually a bug in the sequential method!

**Comment by mpadge** [comment]
``` r
library(geodist)
mat <- matrix(c(-0.193011, 52.15549,
                -0.197722, 52.15395,
                -0.199949, 52.15527,
                -0.199533, 52.15762,
                -0.193205, 52.15757,
                -0.174015, 52.17529),
              ncol = 2, byrow = TRUE)
colnames(mat) <- c("lon","lat")
from <- mat[1:5,]
to <- mat[2:6,]

measures <- c ("haversine", "vincenty", "cheap", "geodesic")
res <- sapply (measures, function (m) {
    dist1 <- geodist::geodist(mat, sequential = TRUE, measure = m)
    dist2 <- geodist::geodist(from, to, paired = TRUE, measure = m)
    dist3 <- geodist::geodist(mat, measure = m)
    dist3 <- dist3 [which (row (dist3) == (col (dist3) + 1))] # off-diagonal
    c (identical(dist1, dist2), identical(dist1, dist3), identical(dist2, dist3))
              })
rownames (res) <- c ("seq-paired", "seq-default", "paired-default")
knitr::kable (res)
```

<table>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">haversine</th>
<th style="text-align: left;">vincenty</th>
<th style="text-align: left;">cheap</th>
<th style="text-align: left;">geodesic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>seq-paired</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td>seq-default</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td>paired-default</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">TRUE</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-04-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It's just a bug with sequential calculation using cheap distances ... now to find what must be an easy fix ...
