### ISSUE TITLE
Speed up R API by allowing direct submission of numeric vector objects

### ISSUE THREAD

**Issue by mpadge** [hypertidy/geodist#22]
Current interface presumes `data.frame` or `matrix` objects at all times, but the [benchmarks of @symbolixAU](https://gist.github.com/SymbolixAU/0f65a431a53da6bdaf5d60b8ff30eba9) show how much can be gained if simple numeric vectors could be submitted -- ~~roughly a 3-times speed gain~~ -- nope, that was an error; actual gains are around 28%. Importantly, submitting numeric matrices is no faster than `data.frame` objects, and it is only direct submission of *vectors* that speeds things up so much. The Q is how such effective speed-ups might be enabled in terms of the R interface here?

**Comment by mdsumner** [comment]
That's interesting, and accords with my sense that *geodist wins when n starts to get BIG". I moved trip over to using geodist recently, and it was clear there was no speed up (from an old copy of the internal sp logic) for small numbers of paired coordinates. 

In [traipse](https://github.com/Trackage/traipse/blob/master/R/track_distance_to.R#L21) I chose this input vector form because it makes sense in `mutate()` workflows and covered the most common "tracking idioms" that I've seen across packages.  Maybe that's a way to go about it? It's sad as I've become accustomed to the geodist ways, but you also get grouping (for sequential metrics like track distance and turning angles) for free - as well as opportunities to parallelize over grouping. 

I don't see the right set of functions / idioms easily though, maybe just lots more functions? When I started traipse I was adamant "forget about Cartesian distance, just use geodesic", but I've been wondering if that was sensible. Another problems is that for traipse both geosphere and geodist are core packages, for bearings and for distance respectively, so as usual the entire R ecosystem needs a bit of a rethink.

**Comment by mdsumner** [comment]
(Sorry was pondering my post before finalizing it and accidentally closed this)

**Comment by mdsumner** [comment]
I do feel that paired and pairwise  *and* sequential are somewhat incongruous in a single function, in traipse that is expressed as `track_distance` (sequential) and `track_distance_to` (paired). It's also really dangerously easy to kick off pairwise for instractable combinations, when paired/sequential is trivial, so perhaps functions like`geodist_to(lon, lat)` would make it clearer that it's pairwise?

**Comment by mpadge** [comment]
Thanks for input @mdsumner - yeah, i suspect you may be right that "lots more functions" might be the only way in the end, especially considering that we should retain any and all ability to `geodist` within piped workflows, which means the core ability to retain simple `geodist(df)`. Direct input of vectors will never be so immediately compatible with piped workflows, and so the current interface *ought not* be compromised in any way by any attempts to address this current issue.

But hey, the package effectively only has one exposed function, `geodist`, so could easily just write a separate interface to C-code as `geodist_vec`. Seems like a workable solution ...

**Comment by mdsumner** [comment]
Yeah I like that, just another function and we can compare - that's neat actually, avoids agonizing over the options. I'm still a bit surprised that unpacking a matrix takes so much time, so I want to understand that properly. (I guess when things are so fast you notice other things that haven't featured before!)

**Comment by mpadge** [comment]
Re: the incongruity: I appreciate that point in principle, but I also think that the current interface is pretty clear and intuitive, and if any particular aspect could be argued to deserve its own distinct function, then so could potentially all, and we'd just end up with four functions instead of one. Through sheer simplicity, I tend to think current functionality is clearer:

``` r
n <- 5
df1 <- data.frame(x = runif (n), y = runif (n))
df2 <- data.frame(x = runif (n), y = runif (n))
library (geodist)

# pairwise comparisons between two objects:
geodist(x = df1, y = df2, paired = TRUE)
#> [1] 108761.88  62955.01  72390.01  67778.92  48078.57

# Comparisons between ALL elements in two objects:
geodist(x = df1, y = df2, paired = FALSE)
#>           [,1]     [,2]     [,3]     [,4]     [,5]
#> [1,] 108761.88 70738.96 58468.46 25043.60 42282.47
#> [2,]  84928.72 62955.01 21872.91 17462.94 15843.12
#> [3,]  43723.70 69428.56 72390.01 86688.17 65322.70
#> [4,]  33887.21 44098.42 63393.28 67778.92 44519.67
#> [5,]  92263.75 47945.71 79458.76 47628.43 48078.57

# Comparisons between ALL elements in single objects:
geodist(x = df1)
#>           [,1]     [,2]      [,3]     [,4]      [,5]
#> [1,]      0.00 42038.05 107599.05 85722.88  34270.48
#> [2,]  42038.05     0.00  70582.15 54165.44  58108.28
#> [3,] 107599.05 70582.15      0.00 26120.83 104885.42
#> [4,]  85722.88 54165.44  26120.83     0.00  79355.69
#> [5,]  34270.48 58108.28 104885.42 79355.69      0.00

# Sequential comparisons along single object:
geodist(x = df1, sequential = TRUE)
#> [1] 42038.05 70582.15 26120.83 79355.69
```

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I think the distinction between 3rd and 4th cases is one of the clearest - more problematic is the distinction between the 1st and 2nd cases, but I don't wanna go there ...

**Comment by mpadge** [comment]
A note on the time differences: The vectors passed to the C function here are `as.vector(matrix(...))` which, in present context, amounts to appending column 2 of matrix on to end of column 1. I guess that in R-internal terms this amounts to reserving a new object of know size (2N), and then copying all elements across, giving an O(2N) operation. The C code here then has a single O(N^2) calculation of one `double` variable ([a cosine value, like here](https://github.com/hypertidy/geodist/blob/master/src/dists_xy.c#L32)), and so if N<sup>2</sup> = 78 in the above code, then N^2 + 2N = 78 + 18 = 96, which is almost exactly the value in the [benchmark](https://gist.github.com/SymbolixAU/0f65a431a53da6bdaf5d60b8ff30eba9). I reckon that should explain it, with key message for our purposes being to always remember or presume that `matrix -> vector` involves a full copy operation.

**Comment by mdsumner** [comment]
You're right, it's supremely clear and waay better than we ever had in R before! The _vec alternative will be more than enough

**Comment by mpadge** [comment]
That commit implements `geodist_vec`, with these results:
``` r
devtools::load_all ("/data/mega/code/repos/hypertidy//geodist", export_all = FALSE)
#> Loading geodist
n <- 1e6
x1 <- runif (n, -0.1, 0.1)
y1 <- runif (n, -0.1, 0.1)
x2 <- runif (n, -0.1, 0.1)
y2 <- runif (n, -0.1, 0.1)
x <- cbind ("x" = x1, "y" = y1)
y <- cbind ("x" = x2, "y" = y2)

# check results are identical:
d1 <- geodist (x, y, paired = TRUE)
d2 <- geodist_vec (x1, y1, x2, y2, paired = TRUE)
identical (d1, d2)
#> [1] TRUE

d1 <- geodist (x, sequential = TRUE)
d2 <- geodist_vec (x1, y1, sequential = TRUE)
identical (d1, d2)
#> [1] TRUE

knitr::kable (rbenchmark::benchmark (
    d <- geodist (x, y, paired = TRUE),
    d <- geodist_vec (x1, y1, x2, y2, paired = TRUE),
    replications = 10) [, 1:4])
```

<table>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">test</th>
<th style="text-align: right;">replications</th>
<th style="text-align: right;">elapsed</th>
<th style="text-align: right;">relative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">d &lt;- geodist_vec(x1, y1, x2, y2, paired = TRUE)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">d &lt;- geodist(x, y, paired = TRUE)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.471</td>
<td style="text-align: right;">6.926</td>
</tr>
</tbody>
</table>

``` r
knitr::kable (rbenchmark::benchmark (
    d <- geodist (x, sequential = TRUE),
    d <- geodist_vec (x1, y1, sequential = TRUE),
    replications = 10) [, 1:4])
```

<table>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">test</th>
<th style="text-align: right;">replications</th>
<th style="text-align: right;">elapsed</th>
<th style="text-align: right;">relative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">d &lt;- geodist_vec(x1, y1, sequential = TRUE)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.105</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">d &lt;- geodist(x, sequential = TRUE)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">2.181</td>
</tr>
</tbody>
</table>

``` r

# smaller matrices for full N^2 calculations:
n1 <- 1e3
n2 <- 2e3
x1 <- runif (n1, -0.1, 0.1)
y1 <- runif (n1, -0.1, 0.1)
x2 <- runif (n2, -0.1, 0.1)
y2 <- runif (n2, -0.1, 0.1)
x <- cbind ("x" = x1, "y" = y1)
y <- cbind ("x" = x2, "y" = y2)

d1 <- geodist (x)
d2 <- geodist_vec (x1, y1)
identical (d1, d2)
#> [1] TRUE

d1 <- geodist (x, y)
d2 <- geodist_vec (x1, y1, x2, y2)
identical (d1, d2)
#> [1] TRUE

knitr::kable (rbenchmark::benchmark (
    d <- geodist (x),
    d <- geodist_vec (x1, y1),
    replications = 10) [, 1:4])
```

<table>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">test</th>
<th style="text-align: right;">replications</th>
<th style="text-align: right;">elapsed</th>
<th style="text-align: right;">relative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">d &lt;- geodist_vec(x1, y1)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">d &lt;- geodist(x)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;">1.014</td>
</tr>
</tbody>
</table>

``` r
knitr::kable (rbenchmark::benchmark (
    d <- geodist (x, y),
    d <- geodist_vec (x1, y1, x2, y2),
    replications = 10) [, 1:4])
```

<table>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">test</th>
<th style="text-align: right;">replications</th>
<th style="text-align: right;">elapsed</th>
<th style="text-align: right;">relative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td style="text-align: left;">d &lt;- geodist_vec(x1, y1, x2, y2)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.274</td>
<td style="text-align: right;">1.161</td>
</tr>
<tr class="even">
<td>1</td>
<td style="text-align: left;">d &lt;- geodist(x, y)</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.236</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The last one is actually slower because of the creation in C of four vectors instead of two in the non-`_vec` version. That extra allocation of extra distinct objects is enough to slow it down. But the `paired` result shows that this is nevertheless really worth doing. Re-opening this issue until this has been documented, including in vignette.

**Comment by mdsumner** [comment]
Neato, someone somewhere mentioned in an SO comment that the matrix/vector form of inputs would not affect performance, and I dismissed it - I need to track it down and eat crow

**Comment by mpadge** [comment]
Ha, yeah, I've learn a lot doing that - vector inputs are better, but only to a point; if C-level code equates to breaking things into too many individually stored objects (vectors), then matrices can in fact be better. The one thing that's not really true at all is that vectors and matrices are equivalent in terms of performance.

**Comment by SymbolixAU** [comment]
I see my work here is done...

related - https://github.com/Rdatatable/data.table/issues/2273 - the `_vec()` functions should naturally fit inside a `data.table` workflow

**Comment by mpadge** [comment]
Closing via #27, which exports new `geodist_vec()` fn
