### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Robinlovelace** [hypertidy/geodist#25]
Hi guys, just wanted to say, huge thanks for this package: it's saved me a huge amount of programming and computer time! This is a godsend for work-in-progress updates to `cyclestreets`, an interface to routing service for cyclists by cyclists by @mvl22 & co:

```r
  dist_list = lapply(coord_list, function(x) {
    geodist::geodist(
      data.frame(x = x[, 1], y = x[, 2]),
      sequential = TRUE
      )}
    )
```

**Comment by mpadge** [comment]
Aw shucks, thanks! Maybe just worth noting that it does not do any intelligent checking for the default `measure = "cheap"`, and this can be *very* divergent beyond about 100km. So worth doing a post-check on results to get max dist, and if too large, explicitly specify alternative `measure`. Which makes me realise that should be rectified, so i'll open a new issue to put a post-check on, and issue warning for when cheapdist might become inaccurate.

**Comment by Robinlovelace** [comment]
Average segment distances are ~20m so should be fine. Plus can compare with actual distances, although those are less accurate, in m. Closing for now!

**Comment by mdsumner** [comment]
YMAL https://github.com/Trackage/traipse
