### ISSUE TITLE
Update CRAN version with geodist_paired_vec

### ISSUE THREAD

**Issue by daniellemccool** [hypertidy/geodist#27]
I'm using geodist in a package that I might eventually want to put on CRAN, but I'd really benefit from the geodist_paired_vec method.  I'm torn between adding it as a github dependency or keeping the current CRAN version.

If there _were_ plans to update it soon, it'd save me the hard decision. :)

**Comment by mpadge** [comment]
Oh, so sorry - i didn't realise that the `paired_vec` method had not been pushed to CRAN. I'll get that there asap, and close this issue as soon as it's up so you'll know. In the meantime, most uses will really not notice any difference between that and passing a `matrix` -- **NOT** `data.frame` -- to the main `geodist` function, unless you really are calculating more than O(10^6-7) or so distances. But it should be up early next week anyway. Thanks for the nudge!

**Comment by mdsumner** [comment]
fwiw I saw this and did a check and revdepcheck on ubuntu with R 4.0.0 and found no problems ;)

**Comment by daniellemccool** [comment]
Thanks so much!  

> In the meantime, most uses will really not notice any difference between that and passing a `matrix` -- **NOT** `data.frame` -- to the main `geodist` function, unless you really are calculating more than O(10^6-7) or so distances. 

For my own purposes, it's a quality of life improvement. I've built everything using data.table because of some unfortunate memory limitations on a secure server. So when it comes to running geodist right now, it looks like this (although I ought to have used matrices here):

`data[, `:=`(dist, geodist::geodist(x = data.table(lon, lat),
                                                   y = data.table(longitude = adjusted_lon, latitude = adjusted_lat), 
                                                   paired = TRUE))]`

It gets a little wordy for me, leading me to miss dumb typos or incorrect variable order. I'm mostly just excited about the improvements to readability for my code! 

Thanks again for the quick reply. I'll wait patiently.

**Comment by mpadge** [comment]
geodist 0.0.4 is [up on CRAN](https://cran.r-project.org/web/packages/geodist/index.html)

``` r
library(geodist)
packageVersion("geodist")
#> [1] '0.0.4'
ls("package:geodist")
#> [1] "geodist"           "geodist_benchmark" "geodist_vec"      
#> [4] "georange"
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks for the push @daniellemccool!

**Comment by mdsumner** [comment]
wooo!

**Comment by daniellemccool** [comment]
Thanks so much!
