### ISSUE TITLE
Updated version of package fails when y coordinate is called ymax

### ISSUE THREAD

**Issue by Robinlovelace** [hypertidy/geodist#33]
Discovered in the slopes package and documented here: https://github.com/ITSLeeds/slopes/issues/25

After some investigation it seems the names of the coordinates are the cause:

``` r
geodist::geodist(c(xmin = -9.2, ymin = 39), c(xmax = -9.1, ymin = 38))
#> Maximum distance is > 100km. The 'cheap' measure is inaccurate over such
#> large distances, you'd likely be better using a different 'measure'.
#>          [,1]
#> [1,] 111472.8
geodist::geodist(c(xmin = -9.2, ymin = 39), c(xmax = -9.1, ymax = 38))
#> Error in find_xy_cols(obj): Unable to determine longitude and latitude columns; perhaps try re-naming columns.
```

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mpadge** [comment]
Sorry, took a few days, but that commit should fix. Thanks again for uncovering

**Comment by Robinlovelace** [comment]
Great fix, thanks @mpadge

**Comment by mpadge** [comment]
Yeah, i remain really committed to the general workflow of "smartly" parsing columns names in most packages, but it is sometimes more prone to bugs than simply insisting on a single hard-coded system. Still worth it I maintain!
