### ISSUE TITLE
add sequential param?

### ISSUE THREAD

**Issue by mpadge** [hypertidy/geodist#4]
`sequential = TRUE` (non-default) would calcualte sequential distances along the rows of a single object, precisely as `geosphere` does it, so would return `n-1` distances rather than the entire `n`-by-`n` matrix. @mdsumner whaddayareckon? Methinks likely quite useful.

**Comment by mdsumner** [comment]
Definitely useful as in I can't live without it! Another case to get right is when have arbitrary edges,  two columns of from/to indexes into a vertex pool. So pairing of coords is needed, and sequential is a special case of that using a lag of 1. I can't see what the best overall design is, can we cover all cases with one engine or does it need different implementations?

**Comment by mpadge** [comment]
Great, how about I do the easy rectangular and sequential stuff to get the grunt implementation optimized, and you can think about and start implementing other cases
