### ISSUE TITLE
units

### ISSUE THREAD

**Issue by mpadge** [hypertidy/geodist#7]
extending from #1, implement a `units` parameter to set user-determined units. This is done very neatly in [`cheap ruler`](https://github.com/mapbox/cheap-ruler-cpp/blob/master/include/mapbox/cheap_ruler.hpp#L39-L64), conveniently giving us our desired list of units to include.

**Comment by edzer** [comment]
Nice package! I would also go for `m` as the default unit since it is the SI base unit.

For conversions or typing units, I'd recommend to go with the [`units` package](https://journal.r-project.org/archive/2016/RJ-2016-061/index.html), which takes care of vectors and matrices.

**Comment by mpadge** [comment]
Thanks @edzer - shall do with `m` as default. `units` is a good suggestion, but we'll handle conversion of units in C just because this package is an exercise in (1) maximal possible speed, so only want one multiplication for each output rather than two; and (2) writing a package entirely free of depenencies

**Comment by edzer** [comment]
In that case, use `m` and don't do unit conversions in this package.
